/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

import buregi.model.hapus_pengguna;
import buregi.model.koneksiDataBase;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Resa Yudha
 */
public class Hapuspelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Hapuspelanggan
     */
    public Connection koneksi;
    hapus_pengguna penggu = new hapus_pengguna();
    public Hapuspelanggan() {
        initComponents();
        tampilpengguna();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idktppengguna = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        keluarmenu = new javax.swing.JButton();
        kemenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hapus Data Pengguna");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 260, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Id KTP Pengguna");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 160, 22);
        getContentPane().add(idktppengguna);
        idktppengguna.setBounds(230, 80, 230, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 690, 320);

        hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hapusbutton1.png"))); // NOI18N
        hapus.setText("jButton1");
        hapus.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hapusbutton2.png"))); // NOI18N
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(620, 540, 80, 40);

        keluarmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit.png"))); // NOI18N
        keluarmenu.setText("jButton2");
        keluarmenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit2.png"))); // NOI18N
        keluarmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarmenuActionPerformed(evt);
            }
        });
        getContentPane().add(keluarmenu);
        keluarmenu.setBounds(500, 540, 100, 40);

        kemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub3.jpg"))); // NOI18N
        kemenu.setText("jButton3");
        kemenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub23.jpg"))); // NOI18N
        kemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemenuActionPerformed(evt);
            }
        });
        getContentPane().add(kemenu);
        kemenu.setBounds(740, 0, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 838, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarmenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_keluarmenuActionPerformed

    private void kemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kemenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_kemenuActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        String idkp = (String) idktppengguna.getText();
        if(penggu.hapus(idkp)){
            JOptionPane.showMessageDialog(rootPane,"Hapus Pengguna Berhasil");
            this.setVisible(false);
            Menu menu = new Menu();
            menu.setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hapuspelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hapuspelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hapuspelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hapuspelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hapuspelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idktppengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluarmenu;
    private javax.swing.JButton kemenu;
    // End of variables declaration//GEN-END:variables
    public void tampilpengguna(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Pelanggan");
        tabel.addColumn("Nama");
        tabel.addColumn("Id KTP");
        tabel.addColumn("Alamat");
        tabel.addColumn("Telephone");

        try{
            koneksi = new koneksiDataBase().condb();
            String sql = "select * from pelanggan order by idpelanggan";
            Statement stat = koneksi.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
        }
        jTable1.setModel(tabel);
    }

}
