/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

import buregi.model.koneksiDataBase;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Resa Yudha
 */
public class InputTempatWisata extends javax.swing.JFrame {

    /**
     * Creates new form InputTempatWisata
     */
    public Connection koneksi;
    
    public InputTempatWisata() {
        initComponents();
        tampilkabupaten();
        tampilwisata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namawisata = new javax.swing.JTextField();
        biayamasuk = new javax.swing.JTextField();
        kabupaten = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kemenu = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        star = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelola Data Tempat Wisata");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 10, 330, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Tempat Wisata");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 169, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kabupaten");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 120, 84, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Biaya Masuk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 98, 22);
        getContentPane().add(namawisata);
        namawisata.setBounds(250, 80, 220, 30);
        getContentPane().add(biayamasuk);
        biayamasuk.setBounds(250, 160, 220, 30);

        kabupaten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Kabupaten" }));
        kabupaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabupatenActionPerformed(evt);
            }
        });
        getContentPane().add(kabupaten);
        kabupaten.setBounds(250, 120, 220, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 232, 690, 260);

        kemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit.png"))); // NOI18N
        kemenu.setText("jButton1");
        kemenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit2.png"))); // NOI18N
        kemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemenuActionPerformed(evt);
            }
        });
        getContentPane().add(kemenu);
        kemenu.setBounds(450, 560, 110, 30);

        selesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai1.png"))); // NOI18N
        selesai.setText("jButton2");
        selesai.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai2.png"))); // NOI18N
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(selesai);
        selesai.setBounds(590, 560, 110, 30);

        star.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub3.jpg"))); // NOI18N
        star.setText("jButton3");
        star.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub23.jpg"))); // NOI18N
        star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActionPerformed(evt);
            }
        });
        getContentPane().add(star);
        star.setBounds(740, 0, 73, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 838, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kabupatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabupatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kabupatenActionPerformed

    private void starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_starActionPerformed

    private void kemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kemenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_kemenuActionPerformed

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        koneksi = new koneksiDataBase().condb();
        String nama = (String) namawisata.getText();
        String kabu = (String) kabupaten.getSelectedItem();
        int biaya = Integer.parseInt(biayamasuk.getText());
        try {
            String input ="insert into tb_wisata (nama,kab,biaya) values('"+nama+"','"+kabu+"','"+biaya+"')";
            Statement stat;
            stat = (Statement) koneksi.createStatement();
            stat.executeUpdate(input);
            JOptionPane.showMessageDialog(rootPane, "Berhasil Memasukan Data Kendaraan Baru");
            this.setVisible(false);
            Menu menu = new Menu();
            menu.setVisible(true);
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(rootPane,"Terjadi Kesalahan"+ex);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputTempatWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputTempatWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputTempatWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputTempatWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputTempatWisata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField biayamasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> kabupaten;
    private javax.swing.JButton kemenu;
    private javax.swing.JTextField namawisata;
    private javax.swing.JButton selesai;
    private javax.swing.JButton star;
    // End of variables declaration//GEN-END:variables
    private void tampilkabupaten(){
        kabupaten.addItem("Denpasar");
        kabupaten.addItem("Tabanan");
        kabupaten.addItem("Badung");
        kabupaten.addItem("Bangli");
        kabupaten.addItem("Buleleng");
        kabupaten.addItem("Gianyar");
        kabupaten.addItem("Jebrana");
        kabupaten.addItem("KarangAsem");
        kabupaten.addItem("Klungkung");
    }
    public void tampilwisata(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Wisata");
        tabel.addColumn("Nama");
        tabel.addColumn("Kabupaten");
        tabel.addColumn("Harga");

        try{
            koneksi = new koneksiDataBase().condb();
            String sql = "select * from tb_wisata order by id_wisata";
            Statement stat = koneksi.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
        }
        jTable1.setModel(tabel);
    }

}
