/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

import buregi.model.input_kendaraan;
import buregi.model.koneksiDataBase;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Resa Yudha
 */
public class KelolaDataKendaraan extends javax.swing.JFrame {

    /**
     * Creates new form KelolaDataKendaraan
     */
    public Connection koneksi;
    input_kendaraan kendaraan = new input_kendaraan();
    
    public KelolaDataKendaraan() {
        initComponents();
        tampilkendaraan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namakendaraan = new javax.swing.JTextField();
        nomorpolisi = new javax.swing.JTextField();
        jumtempatduduk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kemenu = new javax.swing.JButton();
        selesai = new javax.swing.JButton();
        star = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelola Data Kendaraan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 250, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Kendaraan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 70, 210, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nomor Polisi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 110, 170, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Jumlah tempat duduk");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 150, 230, 22);
        getContentPane().add(namakendaraan);
        namakendaraan.setBounds(280, 70, 210, 30);
        getContentPane().add(nomorpolisi);
        nomorpolisi.setBounds(280, 110, 210, 30);
        getContentPane().add(jumtempatduduk);
        jumtempatduduk.setBounds(280, 150, 210, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 200, 690, 310);

        kemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit.png"))); // NOI18N
        kemenu.setText("jButton1");
        kemenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit2.png"))); // NOI18N
        kemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemenuActionPerformed(evt);
            }
        });
        getContentPane().add(kemenu);
        kemenu.setBounds(470, 560, 100, 30);

        selesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai1.png"))); // NOI18N
        selesai.setText("jButton2");
        selesai.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai2.png"))); // NOI18N
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(selesai);
        selesai.setBounds(600, 560, 100, 30);

        star.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub3.jpg"))); // NOI18N
        star.setText("jButton1");
        star.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub23.jpg"))); // NOI18N
        star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActionPerformed(evt);
            }
        });
        getContentPane().add(star);
        star.setBounds(740, 0, 73, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 838, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        koneksi = new koneksiDataBase().condb();
        String nama = (String) namakendaraan.getText();
        String idk = (String) nomorpolisi.getText();
        int jumduk = Integer.parseInt(jumtempatduduk.getText());
        if(kendaraan.input_kend(nama, idk, jumduk)){
            JOptionPane.showMessageDialog(rootPane, "Berhasil Memasukan Data Kendaraan Baru");
            this.setVisible(false);
            Menu menu = new Menu();
            menu.setVisible(true);
        }//TODO add your handling code here:
    }//GEN-LAST:event_selesaiActionPerformed

    private void kemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kemenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_kemenuActionPerformed

    private void starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_starActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaDataKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaDataKendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jumtempatduduk;
    private javax.swing.JButton kemenu;
    private javax.swing.JTextField namakendaraan;
    private javax.swing.JTextField nomorpolisi;
    private javax.swing.JButton selesai;
    private javax.swing.JButton star;
    // End of variables declaration//GEN-END:variables

    public void tampilkendaraan(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Kendaraan");
        tabel.addColumn("ID Polisi");
        tabel.addColumn("Nama");
        tabel.addColumn("Jumlah Kursi");

        try{
            koneksi = new koneksiDataBase().condb();
            String sql = "select * from kendaraan order by id_kendaraan";
            Statement stat = koneksi.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
        }
        jTable1.setModel(tabel);
    }

}
