/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

import buregi.model.input_data_petugas;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import buregi.model.koneksiDataBase;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Resa Yudha
 */
public class Keloladatapetugas extends javax.swing.JFrame {

    /**
     * Creates new form Keloladatapetugas
     */
    
    public Connection koneksi;
    input_data_petugas inputpetugas = new input_data_petugas();
    
    public Keloladatapetugas() {
        initComponents();
        tampilpetugas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namapetugas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idktp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        telepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        selesaiinputpetugas = new javax.swing.JButton();
        gakjadiinputpetugas = new javax.swing.JButton();
        kemenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 630));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kelola Data Petugas");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 260, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Petugas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 90, 130, 22);
        getContentPane().add(namapetugas);
        namapetugas.setBounds(240, 90, 180, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID KTP");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 130, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 170, 80, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telephone");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 210, 100, 22);
        getContentPane().add(idktp);
        idktp.setBounds(240, 130, 180, 30);
        getContentPane().add(alamat);
        alamat.setBounds(240, 170, 180, 30);
        getContentPane().add(telepon);
        telepon.setBounds(240, 210, 180, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 290, 690, 220);

        selesaiinputpetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai1.png"))); // NOI18N
        selesaiinputpetugas.setText("jButton1");
        selesaiinputpetugas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai2.png"))); // NOI18N
        selesaiinputpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiinputpetugasActionPerformed(evt);
            }
        });
        getContentPane().add(selesaiinputpetugas);
        selesaiinputpetugas.setBounds(593, 550, 100, 30);

        gakjadiinputpetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit.png"))); // NOI18N
        gakjadiinputpetugas.setText("jButton2");
        gakjadiinputpetugas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit2.png"))); // NOI18N
        gakjadiinputpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gakjadiinputpetugasActionPerformed(evt);
            }
        });
        getContentPane().add(gakjadiinputpetugas);
        gakjadiinputpetugas.setBounds(470, 550, 110, 30);

        kemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub3.jpg"))); // NOI18N
        kemenu.setText("jButton1");
        kemenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub23.jpg"))); // NOI18N
        kemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemenuActionPerformed(evt);
            }
        });
        getContentPane().add(kemenu);
        kemenu.setBounds(740, 0, 73, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kemenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_kemenuActionPerformed

    private void gakjadiinputpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gakjadiinputpetugasActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_gakjadiinputpetugasActionPerformed

    private void selesaiinputpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiinputpetugasActionPerformed
        koneksi = new koneksiDataBase().condb();
        String nama = (String) namapetugas.getText();
        String id = (String) idktp.getText();
        String alamt = (String) alamat.getText();
        String tlp = (String) telepon.getText();
        if(inputpetugas.input_data(id, nama, alamt, tlp)){
            JOptionPane.showMessageDialog(rootPane,"Berhasil Memasukan Data Petugas");
            this.setVisible(false);
            Menu menu = new Menu();
            menu.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Terjadi Kesalahan");
        }
                    // TODO add your handling code here:
    }//GEN-LAST:event_selesaiinputpetugasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keloladatapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keloladatapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keloladatapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keloladatapetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keloladatapetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton gakjadiinputpetugas;
    private javax.swing.JTextField idktp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kemenu;
    private javax.swing.JTextField namapetugas;
    private javax.swing.JButton selesaiinputpetugas;
    private javax.swing.JTextField telepon;
    // End of variables declaration//GEN-END:variables

    public void tampilpetugas(){
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID Petugas");
        tabel.addColumn("ID KTP");
        tabel.addColumn("Nama");
        tabel.addColumn("Jabatan");
        tabel.addColumn("Telephone");

        try{
            koneksi = new koneksiDataBase().condb();
            String sql = "select id_petugas,id_ktp,nick,jabatan,tlp from karyawan order by id_petugas";
            Statement stat = koneksi.createStatement();
            ResultSet res = stat.executeQuery(sql);
            while(res.next()){
                tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
        }
        jTable1.setModel(tabel);
    }
}
