/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

/**
 *
 * @author Resa Yudha
 */
public class konfirmkelolapelanggan extends javax.swing.JFrame {

    /**
     * Creates new form konfirmkelolapelanggan
     */
    public konfirmkelolapelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        hapuspelanggan = new javax.swing.JButton();
        inputpelanggan = new javax.swing.JButton();
        kemenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu Kelola Data Pelanggan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 80, 340, 29);

        hapuspelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hapusbutton1.png"))); // NOI18N
        hapuspelanggan.setText("jButton2");
        hapuspelanggan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hapusbutton2.png"))); // NOI18N
        hapuspelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapuspelangganActionPerformed(evt);
            }
        });
        getContentPane().add(hapuspelanggan);
        hapuspelanggan.setBounds(120, 210, 140, 50);

        inputpelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/inputbutton1.png"))); // NOI18N
        inputpelanggan.setText("jButton3");
        inputpelanggan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/inputbutton2.png"))); // NOI18N
        inputpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpelangganActionPerformed(evt);
            }
        });
        getContentPane().add(inputpelanggan);
        inputpelanggan.setBounds(460, 210, 140, 50);

        kemenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub3.jpg"))); // NOI18N
        kemenu.setText("jButton1");
        kemenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub23.jpg"))); // NOI18N
        kemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kemenuActionPerformed(evt);
            }
        });
        getContentPane().add(kemenu);
        kemenu.setBounds(740, 0, 80, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 838, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapuspelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapuspelangganActionPerformed
        this.setVisible(false);
        Hapuspelanggan happel = new Hapuspelanggan();
        happel.setVisible(true);
    }//GEN-LAST:event_hapuspelangganActionPerformed

    private void inputpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpelangganActionPerformed
        this.setVisible(false);
        KelolaDataPelanggan pelanggan = new KelolaDataPelanggan();
        pelanggan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_inputpelangganActionPerformed

    private void kemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kemenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_kemenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konfirmkelolapelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konfirmkelolapelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konfirmkelolapelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konfirmkelolapelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konfirmkelolapelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapuspelanggan;
    private javax.swing.JButton inputpelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kemenu;
    // End of variables declaration//GEN-END:variables
}
