/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

import buregi.model.koneksiDataBase;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Resa Yudha
 */
public class LihatDataPerjalanan extends javax.swing.JFrame {

    /**
     * Creates new form LihatDataPerjalanan
     */
    public Connection koneksi;
    public LihatDataPerjalanan() {
        initComponents();
        tableperjalanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        selesaibutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lihat Data Perjalanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 20, 200, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 700, 440);

        selesaibutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai1.png"))); // NOI18N
        selesaibutton.setText("jButton1");
        selesaibutton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Selesai2.png"))); // NOI18N
        selesaibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(selesaibutton);
        selesaibutton.setBounds(580, 560, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/TampilanDefault.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selesaibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaibuttonActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_selesaibuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatDataPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatDataPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatDataPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatDataPerjalanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatDataPerjalanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton selesaibutton;
    // End of variables declaration//GEN-END:variables

public void tableperjalanan(){
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("ID Transaksi");
    tabel.addColumn("ID Pelanggan");
    tabel.addColumn("Nama");
    tabel.addColumn("ID Paket");
    tabel.addColumn("Tgl Berangkat");
    tabel.addColumn("Kendaraan");
    tabel.addColumn("Sopir");
    tabel.addColumn("Biaya");
    
    try{
        koneksi = new koneksiDataBase().condb();
        String sql = "select * from tr_pejalanan order by id_transaksi";
        Statement stat = koneksi.createStatement();
        ResultSet res = stat.executeQuery(sql);
        while(res.next()){
            tabel.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8)});
        }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(rootPane, "gagal tampil data"+ex);
    }
    jTable1.setModel(tabel);
}
}


