/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buregi.form;

import javax.swing.JOptionPane;

/**
 *
 * @author Resa Yudha
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        keloladatapetugas = new javax.swing.JButton();
        inputdataperjalanan = new javax.swing.JButton();
        lihatdataperjalanan = new javax.swing.JButton();
        keloladatakendaraan = new javax.swing.JButton();
        inputtempatwisata = new javax.swing.JButton();
        keloladatapaketwisata = new javax.swing.JButton();
        keloladatapelanggan = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 635));
        getContentPane().setLayout(null);

        keloladatapetugas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keloladatapetugasbutton1.png"))); // NOI18N
        keloladatapetugas.setText("jButton1");
        keloladatapetugas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keloladatapetugasbutton2.png"))); // NOI18N
        keloladatapetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keloladatapetugasActionPerformed(evt);
            }
        });
        getContentPane().add(keloladatapetugas);
        keloladatapetugas.setBounds(60, 230, 140, 70);

        inputdataperjalanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/InputDataPerjalananButton1.png"))); // NOI18N
        inputdataperjalanan.setText("jButton1");
        inputdataperjalanan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/InputDataPerjalananButton2.png"))); // NOI18N
        inputdataperjalanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputdataperjalananActionPerformed(evt);
            }
        });
        getContentPane().add(inputdataperjalanan);
        inputdataperjalanan.setBounds(60, 110, 140, 70);

        lihatdataperjalanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/LihatDataPerjalanan1.png"))); // NOI18N
        lihatdataperjalanan.setText("jButton1");
        lihatdataperjalanan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/LihatDataPerjalanan2.png"))); // NOI18N
        lihatdataperjalanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatdataperjalananActionPerformed(evt);
            }
        });
        getContentPane().add(lihatdataperjalanan);
        lihatdataperjalanan.setBounds(310, 110, 140, 70);

        keloladatakendaraan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/KelolaDataKendaraanbutton1.png"))); // NOI18N
        keloladatakendaraan.setText("jButton1");
        keloladatakendaraan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/KelolaDataKendaraanbutton2.png"))); // NOI18N
        keloladatakendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keloladatakendaraanActionPerformed(evt);
            }
        });
        getContentPane().add(keloladatakendaraan);
        keloladatakendaraan.setBounds(310, 230, 140, 70);

        inputtempatwisata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Inputtempatwisata.png"))); // NOI18N
        inputtempatwisata.setText("jButton1");
        inputtempatwisata.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Inputtempatwisata2.png"))); // NOI18N
        inputtempatwisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputtempatwisataActionPerformed(evt);
            }
        });
        getContentPane().add(inputtempatwisata);
        inputtempatwisata.setBounds(60, 350, 140, 70);

        keloladatapaketwisata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/InputPaketWisata.png"))); // NOI18N
        keloladatapaketwisata.setText("jButton1");
        keloladatapaketwisata.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/InputPaketWisata2.png"))); // NOI18N
        keloladatapaketwisata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keloladatapaketwisataActionPerformed(evt);
            }
        });
        getContentPane().add(keloladatapaketwisata);
        keloladatapaketwisata.setBounds(310, 350, 140, 70);

        keloladatapelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keloladatapelanggan1.png"))); // NOI18N
        keloladatapelanggan.setText("jButton1");
        keloladatapelanggan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keloladatapelanggan2.png"))); // NOI18N
        keloladatapelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keloladatapelangganActionPerformed(evt);
            }
        });
        getContentPane().add(keloladatapelanggan);
        keloladatapelanggan.setBounds(310, 480, 140, 70);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit.png"))); // NOI18N
        logout.setText("jButton1");
        logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Exit2.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(550, 530, 120, 40);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub3.jpg"))); // NOI18N
        home.setText("jButton1");
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/sub23.jpg"))); // NOI18N
        getContentPane().add(home);
        home.setBounds(740, 0, 80, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Dashboard.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 838, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keloladatapetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keloladatapetugasActionPerformed
        this.setVisible(false);
        Konfirmasihapuspetugas kelola = new Konfirmasihapuspetugas();
        kelola.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_keloladatapetugasActionPerformed

    private void keloladatapelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keloladatapelangganActionPerformed
        this.setVisible(false);
        konfirmkelolapelanggan konfirmpelanggan = new konfirmkelolapelanggan();
        konfirmpelanggan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_keloladatapelangganActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.setVisible(false);
        Login_Page keluar = new Login_Page();
        keluar.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void inputdataperjalananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputdataperjalananActionPerformed
        this.setVisible(false);
        Konfirmasikelolaperjalanan perjalanan = new Konfirmasikelolaperjalanan();
        perjalanan.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_inputdataperjalananActionPerformed

    private void lihatdataperjalananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatdataperjalananActionPerformed
        this.setVisible(false);
        LihatDataPerjalanan lihat = new LihatDataPerjalanan();
        lihat.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lihatdataperjalananActionPerformed

    private void keloladatakendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keloladatakendaraanActionPerformed
        this.setVisible(false);
        KelolaDataKendaraan kelolakendaraan = new KelolaDataKendaraan();
        kelolakendaraan.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_keloladatakendaraanActionPerformed

    private void inputtempatwisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputtempatwisataActionPerformed
        this.setVisible(false);
        InputTempatWisata inputwisata = new InputTempatWisata();
        inputwisata.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_inputtempatwisataActionPerformed

    private void keloladatapaketwisataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keloladatapaketwisataActionPerformed
        this.setVisible(false);
        Input_Paket_Wisata inputPW = new Input_Paket_Wisata();
        inputPW.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_keloladatapaketwisataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JButton inputdataperjalanan;
    private javax.swing.JButton inputtempatwisata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keloladatakendaraan;
    private javax.swing.JButton keloladatapaketwisata;
    private javax.swing.JButton keloladatapelanggan;
    private javax.swing.JButton keloladatapetugas;
    private javax.swing.JButton lihatdataperjalanan;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
